name: test

on:

  push:

    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: python -m pip install pytest

      - run: python hello.py

      - run: python myreverse.py

      - run: pytest test_myreverse.py
